### ISSUE TITLE
Spell checking no longer working in 2.17.0

### ISSUE THREAD

**Issue by cdisabatino** [RocketChat/Rocket.Chat.Electron#1426]
## My Setup
- Operating System: Windows 10
- App Version: 2.17.0
- Installation type: exe 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

After updating from 2.16.2 to 2.17.0 the spell checking no longer works when typing a message.
Nothing wrong gets underlined any more. Downgrading to 2.16.2 makes it work again. The problem is identical on colleagues' computers with version 2.17.0.

I tried the different languages, disabling and enabling spell check completely, etc.

Identical to the ticket : https://github.com/RocketChat/Rocket.Chat.Electron/issues/1362

I installed version 2.17.0 manually by following the ticket : https://github.com/RocketChat/Rocket.Chat.Electron/issues/1399#issuecomment-560437363

Thanks

**Comment by nopynoop** [comment]
I can confirm this. It doesn't work.

**Comment by ddbrandonb** [comment]
+1.
We are also seeing some words incorrectly underlined (they are spelled correctly).

**Comment by Forage** [comment]
Looks like a regression indeed. It was fixed in 2.16.1 but got broken again in 2.17.0 (as well as 2.17.1)

**Comment by Have-a-question-about-this-project** [comment]
I also see it in 2.17.1, but can't check my locale is set correctly because of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1441

**Comment by Sierra1011** [comment]
2.17.0 clients in OpenSUSE and Windows 10, 1909 and 1809, spelling functionality broken for me. Can select a language but it doesn't check any words.

**Comment by evaso** [comment]
The same problem for me. Both version 2.17.0 and version 2.17.1 no longer offer spellcheck. The cursor is also no longer visible in the input field.

**Comment by robcalewar** [comment]
Same issues here; I manually installed 2.17.0. right clicking the text field > spelling languages > EN_US is selecting but if I go to 'browse for language' and select 'en_US.dic' from 'C:\Program Files\Rocket.Chat\resources\dictionaries' I get the error 'Error copying dictionary file: filePath.extname is not a function'

**Comment by mcclint680** [comment]
Ditto with the Mac client. Exact same issue

**Comment by metalcated** [comment]
Yep, Windows 10 and Ubuntu.  Same issue.

**Comment by Forage** [comment]
Fixed in 2.17.4

**Comment by nopynoop** [comment]
> Fixed in 2.17.4

For me, it's still not working.

**Comment by cdisabatino** [comment]
For me, not working 2.17.3.

**Comment by robcalewar** [comment]
Rocketchat version 2.17.4
Windows version 1803

Spellchecking still does not work.

With all this said, this error message no longer pops up when performing the same steps.
> 
> 
> Same issues here; I manually installed 2.17.0. right clicking the text field > spelling languages > EN_US is selected but if I go to 'browse for language' and select 'en_US.dic' from 'C:\Program Files\Rocket.Chat\resources\dictionaries' I get the error 'Error copying dictionary file: filePath.extname is not a function'

**Comment by Forage** [comment]
Strange that it isn't working for some of you. I installed 2.17.4 on Ubuntu and even though the custom dictionaries got removed, because they decided to move to bdic format, the default ones like English gives me red underlines for miss spelled words again.

**Comment by brianochs** [comment]
The 2.17.7 update seems have to restored the spell check feature for me on Windows 10.

**Comment by cdisabatino** [comment]
Version 2.17.7 again offers spell check. But very few languages are offered. There is no French while in a previous version, French was offered.

![image](https://user-images.githubusercontent.com/46713357/74314329-94222700-4d75-11ea-99ba-4a6709d3573b.png)

**Comment by Forage** [comment]
So far French has never been included. You must have added it yourself manually in the past.

**Comment by jbpotonnier** [comment]
French was not included, which was OK since it was not getting in the way.
Now it is very irritating, since everything is red.
![image](https://user-images.githubusercontent.com/368382/76079829-ceae6680-5fa5-11ea-988d-d99b8619c266.png)

**Comment by southpaw5271** [comment]
Also having this issue with all users in our server. Mac, Windows, and Linux are impacted.

**Comment by bigornoo** [comment]
Hi,
same issue here : 
macOS 10.14.6, rocket.chat client v. 2.17.9 ; server v. 3.2.1. no French spell checking

**Comment by eholloway135** [comment]
can confirm.

Windows 10 v1903, Rocket.Chat v 2.17.15 and v 2.17.17, no English spell check

**Comment by fenjen** [comment]
Works for me in 2.17.11. But I want it **off** - all the time. Unchecking all languages disables spell check, but after a restart, the language is re-enabled -- and so is spell check 🙄

**Comment by Forage** [comment]
> Works for me in 2.17.11. But I want it **off** - all the time. Unchecking all languages disables spell check, but after a restart, the language is re-enabled -- and so is spell check roll_eyes

Different problem, different issue to create.

**Comment by bellegarde-c** [comment]
Should be really needed to add all available hunspell language dictionnaries.

Or even better, use system dictionnaries on Linux: https://aur.archlinux.org/cgit/aur.git/tree/use-system-dictionaries.patch?h=rocketchat-desktop

**Comment by Forage** [comment]
> Should be really needed to add all available hunspell language dictionnaries.
> 
> Or even better, use system dictionnaries on Linux: https://aur.archlinux.org/cgit/aur.git/tree/use-system-dictionaries.patch?h=rocketchat-desktop

@bellegarde-c been there, won't happen #1077 despite behaviour already being different on different OSes
