### ISSUE TITLE
Starting a new direct message gives "unknown user" error

### ISSUE THREAD

**Issue by th0bse** [RocketChat/Rocket.Chat.Electron#2241]
**Describe the bug**
When trying to start a new direct message with a user I didn't have a previous direct message, I almost always get an "unknown user" error. This error can be resolved by reloading or closing and restarting the application, then the direct message is shown in the sidebar and works as intended.

What operating system and which version? macOS Big Sur 11.6
Which version of Rocket.Chat (Server)? 4.1.2
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.0.3
Is there any setting relevant changed? Not that I know of ?

**To Reproduce**
1. search for a user that you don't have an active direct conversation with
2. start a new direct conversation (just click on a search result to open the conversation)
3. error "unknown user" appears

**Expected behavior**
A new direct conversation should be opened, without the need to reload the application.

**Comment by jeanfbrito** [comment]
This doesnt happens in the browser Rocket.chat? Seems like a problem with Rocket.Chat and not the Desktop app.

**Comment by ankar84** [comment]
Yeap, it's a RC web client issue, not Electron issue
It could be related to https://github.com/RocketChat/Rocket.Chat/issues/22256 which should be fixed by https://github.com/RocketChat/Rocket.Chat/pull/22944 and already in 4.1.2

**Comment by jeanfbrito** [comment]
I will be closing this issue then. If this continue, you can reopen it.

**Comment by tensor5g** [comment]
I am getting a similar error in docker 4.2.0 when starting a DM with a user for the first time, console displays this error 
```Exception while invoking method createDirectMessage 'Invalid user [error-invalid-user]'```
After reloading and attempting to DM again, it works fine.

**Comment by giterium** [comment]
I have the same thing in 4.2.0 (docker)

**Comment by rasos** [comment]
Please re-open, as it is still an issue and seems not to have been fixed by #22944.

**Comment by th0bse** [comment]
I happily would, but I don't have the permissions to do so. Also I have no idea how it actually looks "under the hood", but the statement "it is a Web Client, not an Electron Issue" made by @ankar84 seems off since the problem occurs in the macOS client, not the web client. And it still occurs.

**Comment by ankar84** [comment]
The idea is if that issue happens in web client (in Chrome fir example) that means it is a web client issue, not Electron bug.
So, please try to reproduce it in web client, and if it successfully replicated, then it's not Electron issue, but especially a Web client issue 

Web client issues are fixed in server version updates, so don't wait Web client issues fixes in Electron application updates.

Please try to update your server version to most recent 4.2.2 for now and check issue again.

**Comment by tensor5g** [comment]
Yes, the issue still occurs on 4.2.2

**Comment by tensor5g** [comment]
Issue persists on docker 4.3.0. Here is the exact error from the docker log
```{"level":50,"time":"2021-12-30T04:36:56.367Z","pid":280,"hostname":"1fce38b76d0f","name":"System","msg":"Exception while invoking method createDirectMessage 'Invalid user [error-invalid-user]'"}```

**Comment by jonyjohny** [comment]
I have the same problem. RC server: 4.3.0, client: 3.7.5

{"level":50,"time":"2022-01-05T06:45:03.559Z","pid":151763,"hostname":"xyz","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"} 
{"level":50,"time":"2022-01-05T06:45:03.719Z","pid":151763,"hostname":"xyz","name":"System","msg":"Exception while invoking method createDirectMessage 'Invalid user [error-invalid-user]'"}

**Comment by tensor5g** [comment]
as @ankar84 stated, it doesn't seem like this is a windows client issue, but an issue with the server itself. I think this is the issue we should be tracking https://github.com/RocketChat/Rocket.Chat/issues/23966
