### ISSUE TITLE
Ubuntu 22.04 - system notiffications do not work

### ISSUE THREAD

**Issue by Racer84** [RocketChat/Rocket.Chat.Electron#2536]

**Comment by matthias4217** [comment]
I'm running `3.8.13` on Ubuntu 22.04 too, with Rocketchat `5.3.3`, and I have the same issue. Others have the same issue.

**Comment by pacho2** [comment]
I think it is because Rocket.Chat uses old libappindicator instead of ayatana indicators, and Debian and OpenSuSE migrated to them.
https://wiki.debian.org/Ayatana/IndicatorsTransition

Supposedly this should be fixed when electron-22 will be used:
https://github.com/electron/electron/pull/36333

Or if the commit is backported

**Comment by jeanfbrito** [comment]
We will be updating the Electron to v22 on the next release. I already made the update in the code, I will test on Ubuntu to see if this fixes it.

**Comment by G2G2G2G** [comment]
It will fix some things and break other things just fyi. https://github.com/electron/electron/issues/36602
update breaks several screen related things with wayland as well as several DEs and window managers etc. Electron should just add an actual fallback to the old https://launchpad.net/libappindicator or whatever

**Comment by jeanfbrito** [comment]
Hello, we had some issues with Electron v22 and we rolled back to Electron v21.
Please update to the version 3.8.16 of the Desktop app and see of this still happens.

**Comment by Racer84** [comment]
Updated to 3.8.16, restared. Nothing's changed - still no notifications.
