### ISSUE TITLE
Updates on macOS do not install

### ISSUE THREAD

**Issue by bbrendon** [RocketChat/Rocket.Chat.Electron#955]
## My Setup
- Operating System: 10.13.6
- App Version: 2.14.0 (previous version also has this issue)
- Installation type:  dmg

- [ x] I have tested with the latest version
- [ x] I can simulate the issue easily

### Current Behavior
0. Click on rocket chat icon.
1. New update is available!
2. Click install update ... blah blah. you will be notified when its ready...
3. Click install now.
4. Program closes.
5. Click on rocket chat icon.
6. Goto step #1. (repeat forever).

### Expected Behavior
Not an endless loop as described above.

I did figure out a workaround. Basically if you run chat from the command line, a zip file is listed. You can download the zip file and uncompress/install manually which installs the update!! Yay!

**Comment by tassoevan** [comment]
It was fixed in #936, but:

> Unfortunately, autoupdate fixes can't be applied backwardly. Therefore, versions listed in #894 will fail on update regardlessly; we advise users to click the "Install later" button to update.

As many users keep reporting this, I'll keep the issue until release 2.14.2 to confirm that everything is fine.

**Comment by szhorvat** [comment]
This is still broken in 2.15.2.

**Comment by dudognon** [comment]
And in 2.16.0.

**Comment by sunergeo** [comment]
I have a similar problem ... I get the prompt for updating to a newer version, but the button doesn't do anything when I click on it.  It doesn't close the window, doesn't start the update process ... it simply does nothing.

**Comment by szhorvat** [comment]
Still broken. I get a notification that 2.17 is available. I click "Install Update". It tells me to wait for a notification that the update is ready. When that notification comes, I click "Install Now", but nothing at all happens.

Does auto-update work for anyone at all on macOS?

@tassoevan claimed that this was already fixed in 2.14.2, but that's not the case.

**Comment by szhorvat** [comment]
I should note that the usual end result is that first I go to https://rocket.chat/install to try to download it manually, discover that this website does not have the latest version, so finally I click "Skip this version" and end up not updating at all. By the time  https://rocket.chat has this version, I will have forgotten about it.

**Comment by szhorvat** [comment]
Still broken in 2.17.7. Will this ever be fixed? Does it work for anyone at all?

**Comment by rmeush** [comment]
> 
> 
> Still broken in 2.17.7. Will this ever be fixed? Does it work for anyone at all?

Still broken in 2.17.9 as well.  Download from Rocket.Chat/install, install it and immediately says update to 2.17.10 is available but no go.  Very frustrating for all my end users who are not tech savvy...

**Comment by szhorvat** [comment]
Yes, and there are countless issues opened for this problem.

@tassoevan Can you at least give a response here? Why is this issue not being taken seriously? For as long as I have been using RocketChat, it has never ever updated correctly.

**Comment by tassoevan** [comment]
@szhorvat I'm still trying to make this error happen in my tests. I've installed the app on macOS Catalina 10.15.5 at version 2.17.9 from the DMG file and the update to 2.17.10 ran smoothly. Is any of this numbers slightly different from your setup?

**Comment by bbrendon** [comment]
@szhorvat If it makes you feel any better it doesn't work on Windows either :)

**Comment by rmeush** [comment]
> 
> 
> @szhorvat If it makes you feel any better it doesn't work on Windows either :)

To be honest i didn't even notice the title of the thread.  I had been looking at so many different threads about it and just posted to this one.  I have Windows as well.  Super frustrating.

**Comment by joe-dsr** [comment]
Still broken for 2.17.11, on Windows 10. Any Updates on how to fix it?

**Comment by bbrendon** [comment]
Is this still a problem? I haven't been using a mac much lately. Can I close this?

**Comment by joe-dsr** [comment]
For me it is still a problem :/

**Comment by szhorvat** [comment]
> Still broken for 2.17.11

How can you tell, given that 2.17.11 is the newest version (i.e. it won't update to anything)?

**Comment by joe-dsr** [comment]
> > Still broken for 2.17.11
> 
> How can you tell, given that 2.17.11 is the newest version (i.e. it won't update to anything)?

I have Version 2.17.7 and the update to 2.17.11 won't work. I'm sorry for the misunderstanding.

**Comment by bbrendon** [comment]
@szhorvat its not broken for him on Macos. Its broken on Windows for him. He just hi-jacked this thread lol.

**Comment by szhorvat** [comment]
I also had version 2.17.7, in which update is broken. I only upgraded to 2.17.11 yesterday. The reason for the upgrade delay: when a new-version notification comes, the new version is typically not available for direct download yet. Auto-update does not work either (it never has, for me). Thus, there is simply no way to update it at this point. Eventually, I get tired of the notification and disable it.

**Comment by szhorvat** [comment]
Still broken in 3.0.6, won't update to 3.0.7.

Sadly, it is illustrative of the general quality of RocketChat.

**Comment by szhorvat** [comment]
In 3.0, the "Skip This Version" button is also broken, see #1871

**Comment by szhorvat** [comment]
Still broken in 3.1.1, but at this point it's quite clear that this whole issue tracker is just for show. None of the issues are being handled. I find it quite disrespectful to users to let them waste their time writing clear issue reports that the company (apparently) has no intention of looking at anyway.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Comment by szhorvat** [comment]
@jeanfbrito For a few versions now, this is what happens:

After clicking the button to install the update, the RocketChat window may or may not disappear, but RocketChat will not exit. If I quit it manually, it re-launches immediately with the new version. 

So it does update, but not everything works correctly.

**Comment by jeanfbrito** [comment]
Yep, I'm tracking this, seems like a electron-builder issue on macos, that is not closing the application to restart.

**Comment by pjv** [comment]
FWIW, the macos in-app update has never once worked correctly. Other electron apps somehow update fine. I have a bunch of them and the rocketchat electron app is the only one that does not update.

Here’s what happens (this is 100% independent of version of either rocketchat or macos): 

1. start the app and get a notification that there is an update available
2. click update and get a notice that i will be informed when the update is ready
3. get notice and click update now
4. the RC **window** closes, but the process **does not** quit (see screenshot below) - stays this way forever
<img width="487" alt="SCR-20230406-fdcj" src="https://user-images.githubusercontent.com/327716/230344541-6af81e07-117a-431f-b8f2-8c4c67f798e6.png">

After that point - SOMETIMES - if you manually quit and restart the app the update will have taken place. More often when you restart the app you are at the old version still and you get the notification that an update is available. When you click update, you immediately get the notice that the update is ready - iow, the downloaded update is still available and doesn’t appear to need to be downloaded again.

It’s annoying not to have a relatively smooth and reliable update process five years after this issue was started and given the fact that there are hundreds of open source electron apps that can successfully self-update. Just copy someone elses working code.

**Comment by jeanfbrito** [comment]
@pjv Pull requests are always welcome.

**Comment by szhorvat** [comment]
@jeanfbrito Many of us are not using RocketChat by choice, but because it's the system our employer (which is paying for it) happens to have. Such a "fix it yourself" attitude is not improving my confidence in it, quite the opposite.

**Comment by pjv** [comment]
@jeanfbrito sorry, i totally would fix this for you and send a PR if were a js/ts developer but I'm afraid it’s outside my area. If you want to rebuild this thing in python…

given that i mostly have no idea what I'm doing with `ts` this might be a dumb question, but you are pulling in the electron updater here:

https://github.com/RocketChat/Rocket.Chat.Electron/blob/681bd64f1aebdb67b84ada70c6b67ce61f5c2c46/src/updates/main.ts#L5

…and most of the code i am seeing in stackoverflow issues and the electron docs says to pull it in like this:

`const { autoUpdater } = require("electron-updater");`

is that doing exactly the same thing (it wouldn’t be in python)?

See also this SO which seems like it exactly describes what I am seeing and has a couple of workarounds that devs used to get past it: https://stackoverflow.com/questions/53852939/electron-auto-updater-not-installing-in-osx

**Comment by jeanfbrito** [comment]
> @jeanfbrito Many of us are not using RocketChat by choice, but because it's the system our employer (which is paying for it) happens to have. Such a "fix it yourself" attitude is not improving my confidence in it, quite the opposite.

Please ask the employer to open a ticket in support. It will help us to prioritize issues like this.

**Comment by jeanfbrito** [comment]
> @jeanfbrito sorry, i totally would fix this for you and send a PR if i were a js/ts developer but I'm afraid it’s outside my area. If you want to rebuild this thing in python…
> 
> given that i mostly have no idea what I'm doing with `ts` this might be a dumb question, but you are pulling in the electron updater here:
> 
> https://github.com/RocketChat/Rocket.Chat.Electron/blob/681bd64f1aebdb67b84ada70c6b67ce61f5c2c46/src/updates/main.ts#L5
> 
> …and most of the code i am seeing in stackoverflow issues and the electron docs says to pull it in like this:
> 
> `const { autoUpdater } = require("electron-updater");`
> 
> is that doing exactly the same thing (it wouldn’t be in python)?
> 
> See also this SO which seems like it exactly describes what I am seeing and has a couple of workarounds that devs used to get past it: https://stackoverflow.com/questions/53852939/electron-auto-updater-not-installing-in-osx

I really thought that this was fixed, a long time that I dont get any complain.
Thanks for pointing it.

I dont understood the python questions. Please could you clarify?

**Comment by pjv** [comment]
FWIW, just now, for the first time ever that I can recall, the Mac app successfully completed a normal self-update from version 3.9.3 to 3.9.4.

**Comment by jeanfbrito** [comment]
Update on this: a fix is up in #3431, with the root cause identified.

Short version — the macOS install path was calling Electron's native `autoUpdater` directly, but `electron-updater`'s `MacUpdater` already owns that same singleton and installs through its own `quitAndInstall()` (the only path that actually hands the downloaded update to Squirrel). Reaching around it meant the app quit without installing, so the same update was offered again on the next launch — the loop described in this thread. It came from a change in April 2023 that was never validated.

Two things worth being straight about:

1. This is targeted at the release **after** 4.16.0, not the current one. The fix cannot be verified by automated tests — the install path has no test coverage, and it only reproduces on a packaged, signed build against a real update feed. Given that a mistake here costs people the ability to update in-app at all, it is getting a full validation pass rather than being rushed into the cycle that is already in progress.
2. Until then the workarounds in this thread still apply: download and install the new version manually.

Leaving this open until the fix has shipped and been confirmed in the wild.
